#cloud-config
hostname: registry
manage_etc_hosts: true
apt_proxy: http://172.16.16.1:8000/
http_proxy: http://172.16.16.1:8000/
_foo: &SSH_KEY "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC5eevkMmUlTxruhespUgHPGO3y3db7hLlq0IPu2WmTf+8YW9MM8/RddGvf2Pwshe7uIz1RhALBluuEXyZXM4ZL4ePiktxUFRKy9a/BnphR/RsAxKQ+HRAAwXheEJ6q3vmjlIMG5GOJhn+br6lMtr/ojDwHrfC1NrSFr/jZkRR5K218Yt33Y7AzZm+ahVkZUHIbpQs4XehBThnMl2enxfum00pGChQJIlDL2jM4ZLMGTvbXe3Zv+70osS0+UDpO8di2CLxi42sDoquNcCvd4KLpG5droqJwf4WRmhleLvkW0H5rP1diUbO5Btu3nJMZVlBZLCSLeI5QKsaN81YwHJsf jujumanage@um-cloud-maas"

groups:
  - umcloud
users:
  - name: ubuntu
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - *SSH_KEY
    ssh-import-id: [jjo, navarrow]
    lock_passwd: true

  - name: umcloud
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - *SSH_KEY
    ssh-import-id: [jjo, navarrow]
    primary-group: umcloud
    lock_passwd: true

_foo: &DEPLOY_SH |
  #!/bin/bash
  echo "*** INFO: BEGIN $0 $*"
  #Deployamos docker 
  sudo apt-get update
  sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  echo "deb https://apt.dockerproject.org/repo ubuntu-xenial main" | sudo tee /etc/apt/sources.list.d/docker.list
  sudo apt-get update
  sudo apt-get install -y docker-engine
  sudo usermod -aG docker ubuntu
  sudo systemctl restart docker

write_files:
  - content: *DEPLOY_SH
    path: /usr/local/src/deploy.sh
    permissions: '0755'

chpasswd:
  list: |
    umcloud:umcloud
  expire: False

runcmd:
  - [ /usr/local/src/deploy.sh ]
