#cloud-config
hostname: sapito
manage_etc_hosts: true
apt_proxy: http://172.16.16.1:8000/
http_proxy: http://172.16.16.1:8000/
_foo: &SSH_KEY "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC5eevkMmUlTxruhespUgHPGO3y3db7hLlq0IPu2WmTf+8YW9MM8/RddGvf2Pwshe7uIz1RhALBluuEXyZXM4ZL4ePiktxUFRKy9a/BnphR/RsAxKQ+HRAAwXheEJ6q3vmjlIMG5GOJhn+br6lMtr/ojDwHrfC1NrSFr/jZkRR5K218Yt33Y7AzZm+ahVkZUHIbpQs4XehBThnMl2enxfum00pGChQJIlDL2jM4ZLMGTvbXe3Zv+70osS0+UDpO8di2CLxi42sDoquNcCvd4KLpG5droqJwf4WRmhleLvkW0H5rP1diUbO5Btu3nJMZVlBZLCSLeI5QKsaN81YwHJsf jujumanage@um-cloud-maas"
_foo: &NOVA_RC |

_foo: &DEPLOY_SH |
  #!/bin/bash
  nova_rc='# Poner credenciales de cloud en las dos lineas de abajo
  export OS_USERNAME=USUARIO
  export OS_PASSWORD=PASSWORD
  export OS_TENANT_NAME=${OS_USERNAME}_project
  export OS_REGION_NAME=um-cloud
  export OS_AUTH_URL=http://172.16.16.192:5000/v2.0'

  echo "*** INFO: BEGIN $0 $*"
  (umask 0077; cd /home; for user in * ; do f=$user/$user.novarc; echo "$nova_rc" > $f; chown $user $f;done)
  echo "*** INFO: END $0 $*"

groups:
  - umcloud

users:
  - name: ubuntu
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - *SSH_KEY
    ssh-import-id: [jjo, navarrow]
    lock_passwd: true
# From vim ->
# :r !./csv-to-tenants.sh
  - { name: jjo, gecos: "juan.ciarlante@um.edu.ar", ssh-import-id: ["jjo"], shell: /bin/bash, primary-group: umcloud }
  - { name: navarrow, gecos: "diego.navarro@um.edu.ar", ssh-import-id: ["navarrow"], shell: /bin/bash, primary-group: umcloud }

write_files:
  - content: *DEPLOY_SH
    path: /usr/local/src/deploy.sh
    permissions: '0755'

# Optimization speed up apt by shortcutting fsync() calls/etc
apt_get_wrapper:
  command: eatmydata
  enabled: True

packages:
  - curl
  - vim-nox
  - screen
  - tmux
  - fping
  - git-core
  - python3-keystoneclient
  - python3-novaclient
  - jq
#  - python3-neutronclient
#  - python3-glanceclient
#  - python3-swiftclient
#  - python3-heatclient
#  - python3-openstackclient

runcmd:
  - [ /usr/local/src/deploy.sh ]
