#cloud-config
hostname: db
manage_etc_hosts: true
apt_proxy: http://172.16.16.1:8000/
http_proxy: http://172.16.16.1:8000/
_foo: &SSH_KEY "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC5eevkMmUlTxruhespUgHPGO3y3db7hLlq0IPu2WmTf+8YW9MM8/RddGvf2Pwshe7uIz1RhALBluuEXyZXM4ZL4ePiktxUFRKy9a/BnphR/RsAxKQ+HRAAwXheEJ6q3vmjlIMG5GOJhn+br6lMtr/ojDwHrfC1NrSFr/jZkRR5K218Yt33Y7AzZm+ahVkZUHIbpQs4XehBThnMl2enxfum00pGChQJIlDL2jM4ZLMGTvbXe3Zv+70osS0+UDpO8di2CLxi42sDoquNcCvd4KLpG5droqJwf4WRmhleLvkW0H5rP1diUbO5Btu3nJMZVlBZLCSLeI5QKsaN81YwHJsf jujumanage@um-cloud-maas"
_foo: &DEPLOY_SH |
  #!/bin/bash
  echo "*** INFO: BEGIN $0 $*"
  #Ponemos el mysql a atender por la red
  sed -i.bak 's/127.0.0.1/0.0.0.0/g' /etc/mysql/mysql.conf.d/mysqld.cnf
  #Restarteamos
  /etc/init.d/mysql restart
  
  echo "GRANT ALL PRIVILEGES ON *.* TO 'webapp'@'%' IDENTIFIED BY 'supersecretisimo';" | mysql -u root
  echo "DROP DATABASE webapp_db; " | mysql -u root
  echo "CREATE DATABASE webapp_db" | mysql -u root
  echo "*** INFO: $(set -x; avahi-resolve -4 -n db.local)"
  echo "*** INFO: END $0 $*"

bootcmd:
 - cloud-init-per once pkgs_install apt-get install -qy avahi-daemon avahi-utils

groups:
  - umcloud
users:
  - name: ubuntu
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - *SSH_KEY
    ssh-import-id: [jjo, navarrow]
    lock_passwd: true

  - name: umcloud
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - *SSH_KEY
    ssh-import-id: [jjo, navarrow]
    primary-group: umcloud
    lock_passwd: true

write_files:
  - content: *DEPLOY_SH
    path: /usr/local/src/deploy.sh
    permissions: '0755'

chpasswd:
  list: |
    umcloud:umcloud
  expire: False
packages:
  - avahi-daemon
  - avahi-utils
  - mysql-server

runcmd:
  - [ /usr/local/src/deploy.sh ]
