apiVersion: v1
kind: Service
metadata:
  labels:
    name: myapp-svc
  name: myapp-svc
spec:
  type: LoadBalancer
  ports:
    # The port that this service should serve on.
    - port: 80
      targetPort: myapp
      protocol: TCP
  # Label keys and values that must match in order to receive traffic for this service.
  selector:
    app: myapp
