apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
    spec:
      restartPolicy: Always
      containers:
        - name: myapp
          image: gcr.io/noble-office-138223/myapp:latest
          ports:
            - name: myapp
              containerPort: 80
          env:
            - name: APP_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: app-db-host
            - name: APP_DB_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: app-db-user
            - name: APP_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: app-db-password
            - name: APP_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: app-db-name
          volumeMounts:
          - mountPath: /var/www/html/
            name: git-volume  
      volumes:
        - name: secret-volume
          secret:
            secretName: app-secret
        - name: git-volume
          gitRepo:
            repository: "https://github.com/IBM-Bluemix/php-mysql.git" 
