apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: db-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      restartPolicy: Always
      containers:
        - name: mysql
          image: mysql:5.6
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: db-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: db-name
          ports:
            - name: mysql
              containerPort: 3306
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/mysql

      volumes:
        - name: db-storage
          gcePersistentDisk:
            pdName: mysql-disk
            fsType: ext4
        - name: secret-volume
          secret:
            secretName: app-secret
