#! /bin/sh
### BEGIN INIT INFO
# Provides:          consul
# Required-Start:    $syslog $time $remote_fs
# Required-Stop:     $syslog $time $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Services/nodes/kv discovery and storage
# Description:       Debian init script for the consul agent
### END INIT INFO
#
# Author:            Diego Navarro <navarrow@gmail.com>
#

PATH=/bin:/usr/bin:/sbin:/usr/sbin
DAEMON=/usr/local/sbin/consul
PIDFILE=/var/run/consul

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

case "$1" in
  start)
        log_daemon_msg "Starting consul agent" "consul"
        start_daemon -s -p $PIDFILE $DAEMON agent -config-dir /etc/consul.d -client 0.0.0.0
        log_end_msg $?
    ;;
  stop)
        log_daemon_msg "Stoping consul agent" "consul"
        killproc -p $PIDFILE $DAEMON
        log_end_msg $?
    ;;
  force-reload|restart)
    $0 stop
    $0 start
    ;;
  status)
    status_of_proc -p $PIDFILE $DAEMON consul && exit 0 || exit $?
    ;;
  *)
    echo "Usage: /etc/init.d/consul {start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac
exit 0
                          
